# Generated by Django 4.2.9 on 2024-02-22 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_course_owner_lessons_owner'),
        ('users', '0004_subscribe_is_signed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribe',
            new_name='Subscription',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'course')},
        ),
    ]
