# Generated by Django 4.2.9 on 2024-02-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_subscribe_subscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'Оплата', 'verbose_name_plural': 'Оплаты'},
        ),
    ]
