# Generated by Django 4.2.9 on 2024-02-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_remove_lessons_course_lessons_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='ссылка на видео'),
        ),
    ]
